class InternalException(Exception):
    pass


class PlayerAlreadyExists(InternalException):
    pass
